language: android
sudo: false
android:
  components:
    - tools
    - platform-tools
    - android-21
    #- android-17
    - android-28
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
    # The BuildTools version used by the project
    - build-tools-28.0.3

    # The SDK version used to compile the project
    - android-26.1.1

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # System Image
    - sys-img-armeabi-v7a-android-17
before_install:
- yes | sdkmanager "platforms;android-28"

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  
  env:
    global:
      - ANDROID_ABI=google_apis/armeabi-v7a
      - ANDROID_API_LEVEL=21
