language: android
android:
  components:
    # - tools
    # - platform-tools

    # The BuildTools version used by the project
    - build-tools-26.0.2

    # The SDK version used to compile the project
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-26
    - sys-img-armeabi-v7a-android-17
