language: android
android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by the project
    - build-tools-28.0.3

    # The SDK version used to compile the project
    - android-26.1.1

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-26
    - sys-img-armeabi-v7a-android-17
before_install:
- mkdir -p "$ANDROID_SDK/licenses"
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"