language: android
android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by the project
    - build-tools-28.0.3

    # The SDK version used to compile the project
    - android-26.1.1

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
before_install:
- yes | sdkmanager "platforms;android-28"